baseURL = 'https://davidschober.github.io/recipes/'
languageCode = 'en-us'
title = 'Recipes'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Categories"
    pre = "edit"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Recipes from the family"
