baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Recipes'

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Recipes from the family"
