baseURL = 'https://davidschober.github.io/recipes/'
languageCode = 'en-us'
title = 'Recipes'

[mediaTypes]
  [mediaTypes."text/markdown"]
  suffixes = ["md","markdown"]
[outputFormats.markdown]
  mediaType = "text/markdown"
  baseName = "index"
  isPlainText = true

[outputs]
  home = ["HTML", "RSS", "JSON", "markdown"]

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Categories"
    pre = "edit"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Recipes from the family"
